site_name: Carrion Crown Wiki
site_description: Pathfinder 1e campaign wiki
site_url: https://ahmfr0636.github.io/arodenites.github.io/
repo_url: https://github.com/ahmfr0636/arodenites.github.io
docs_dir: docs
edit_uri: edit/main/docs/
use_directory_urls: false

theme:
  name: material
  features:
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - search.suggest
    - search.highlight
    - content.action.edit
    - content.code.copy
  palette:
    scheme: slate
    primary: black
    accent: amber

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - tables
  - toc:
      permalink: true

extra_css:
  - stylesheets/extra.css

plugins:
  - search

nav:
  - Home: home.md
  - Overview: carrion-crown/overview.md
  - Party:
      - carrion-crown/party/index.md
      - Herzem al-Gaib: carrion-crown/party/herzem-al-gaib.md
      - Elroth Mornros: carrion-crown/party/elroth-mornros.md
      - Thomas Ruckus: carrion-crown/party/thomas-ruckus.md
      - Darian Vargo: carrion-crown/party/darian-vargo.md
      - Ronin Olaru: carrion-crown/party/ronin-olaru.md
      - Allies:
          - carrion-crown/party/allies/index.md
          - David: carrion-crown/party/allies/david.md
          - Hippogriff: carrion-crown/party/allies/hippogriff.md
  - Timeline: carrion-crown/timeline.md
  - Sessions:
      - carrion-crown/session/index.md
      - Session 1: carrion-crown/session/session-1.md
  - Locations:
      - carrion-crown/locations/index.md
      - Ravengro & Harrowstone:
          - carrion-crown/locations/ravengro-and-harrowstone/index.md
          - General Info & Story: carrion-crown/locations/ravengro-and-harrowstone/general-info-and-story.md
          - NPCs:
              - carrion-crown/locations/ravengro-and-harrowstone/npcs/index.md
              - Friendly: carrion-crown/locations/ravengro-and-harrowstone/npcs/friendly.md
              - Neutral: carrion-crown/locations/ravengro-and-harrowstone/npcs/neutral.md
              - Enemy: carrion-crown/locations/ravengro-and-harrowstone/npcs/enemy.md
  - Organizations:
      - carrion-crown/organizations/index.md
      - Whispering Way: carrion-crown/organizations/whispering-way.md
  - Mobs: carrion-crown/mobs.md
